{ lib }: {
  username = "mochou";
  userfullname = "mochou aaaaaa";
  useremail = "mm.mochou@gmail.com";
  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$CU..../....eljcZ6wMdzMIITQt.XFsn1$wDJIAx4MGcgDInqjtURmobO4JcYG/g9Z3OJUoIjcXZ5";

  # mac 上不使用
  jetbrains = {
    enable = false;
    pycharm = true;
    clion = false;
    datagrip = true;
    goland = true;
  };

  dotfilePath = "/home/mochou/Code/Projects/source/dotfile";

  # hyprland, kde
  desktop = "hyprland";

  disk = {
    enable = false;
    name = "sda";
    filesystem = "ext4";
  };

  networking = {
    defaultGateway = "192.168.1.1";
    nameservers = [ "8.8.8.8" "8.8.4.4" ];

    mingzi = {
      useDHCPv6 = true;
      useDHCP = true;
      ipv4.addresses = [
        {
          address = "192.168.1.100";
          netmask = "255.255.255.0";
        }
      ];
    };
  };
}
