{lib}: {
  homeVersion = "24.11";

  username = "mochou";
  userfullname = "mochou aaaaaa";
  useremail = "mm.mochou@gmail.com";
  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$CU..../....eljcZ6wMdzMIITQt.XFsn1$wDJIAx4MGcgDInqjtURmobO4JcYG/g9Z3OJUoIjcXZ5";
}
